var fs = require("fs")
// fs.mkdirSync("node1")
// fs.writeFileSync("node1/write.txt", "abc")
// fs.appendFileSync("node1/write.txt", "abc")
// data = fs.readFileSync("node1/write.txt", "utf-8")
// console.log(data.toString())
// console.log(data)
// fs.renameSync("node1/write.txt", "readw.txt")
// fs.unlinkSync("readw.txt")
fs.rmdirSync("node1")